# Generated by Django 4.2.6 on 2024-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='latitue',
            new_name='latitude',
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
