# Generated by Django 4.2.6 on 2024-05-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_latitue_owner_latitude_alter_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='capacity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
