# Generated by Django 4.2.6 on 2024-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('facility', models.CharField(max_length=20)),
            ],
        ),
    ]
